#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

panel_link("webhosting", "manager");

for  my $event (qw(
    webhosting-modify smeserver-webhosting-update
    ))
{
    #we can avoid those 2 as we are tricking ourself as ibay-modify and it will do those and php 
    #templates2events("/etc/httpd/conf/httpd.conf", $event);
    #safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith");
    event_link("webhosting-php-expand", $event, "05");
    event_link("webhosting-php-adjust", $event, "90");
}
$event="smeserver-webhosting-update";
event_link("navigation-conf", $event, "70");
# for smeserver-manager
safe_symlink('restart', "root/etc/e-smith/events/$event/services2adjust/smanager");
event_link('navigation2-conf', "$event", '80');
event_link('routes2-conf', "$event", '80');
event_link('locales2-conf', "$event", '80');
